env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  import: false ,
  extensions: false,
}
