env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: false
  import: false 
  extensions: false
}
